12/10/2024 06:09:16 - WARNING - __main__ -   device: cuda, n_gpu: 2
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at /root/local_model/codebert-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
12/10/2024 06:09:19 - INFO - __main__ -   Training/evaluation parameters Namespace(train_data_file='/root/sy/ctx_java_dataset/train_fold_1.csv', output_dir='../results/saved_models', model_type='roberta', block_size=512, eval_data_file='/root/sy/ctx_java_dataset/test_fold_1.csv', test_data_file='/root/sy/ctx_java_dataset/test_fold_1.csv', model_name='codebert_ctx1.bin', model_name_or_path=None, config_name='', use_non_pretrained_model=False, tokenizer_name='', code_length=256, do_train=True, do_eval=False, do_test=True, evaluate_during_training=True, do_local_explanation=False, reasoning_method=None, train_batch_size=32, eval_batch_size=16, gradient_accumulation_steps=1, learning_rate=2e-05, weight_decay=0.0, adam_epsilon=1e-08, max_grad_norm=1.0, max_steps=-1, warmup_steps=0, seed=123456, epochs=10, effort_at_top_k=0.2, top_k_recall_by_lines=0.01, top_k_recall_by_pred_prob=0.2, do_sorting_by_line_scores=False, do_sorting_by_pred_prob=False, top_k_constant=10, num_attention_heads=12, write_raw_preds=False, use_word_level_tokenizer=False, use_non_pretrained_tokenizer=False, n_gpu=2, rq='ctx_1', device=device(type='cuda'))
Traceback (most recent call last):
  File "/root/sy/ptw4awi/1_validity/CodeBert/codebert_main.py", line 464, in <module>
    main()
  File "/root/sy/ptw4awi/1_validity/CodeBert/codebert_main.py", line 435, in main
    train_dataset = TextDataset(tokenizer, args, file_type='train')
  File "/root/sy/ptw4awi/1_validity/CodeBert/codebert_main.py", line 66, in __init__
    df = pd.read_csv(file_path)
  File "/root/anaconda3/envs/LLM/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/anaconda3/envs/LLM/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/root/anaconda3/envs/LLM/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/root/anaconda3/envs/LLM/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/root/anaconda3/envs/LLM/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/root/sy/ctx_java_dataset/train_fold_1.csv'
